services:
  app:
    build: .
    ports:
      - 31337:31337
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: WisHBrAdhOtalMaNOste
